//This code was generated by MS-Builder
package com.amdocs.digital.ms.coe.dashboard.couchbase.config;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Scope;

import com.amdocs.digital.ms.coe.dashboard.business.repository.dto.interfaces.IAdminDTO;
import com.amdocs.digital.ms.coe.dashboard.business.repository.dto.interfaces.IEmployeeDTO;
import com.amdocs.digital.ms.coe.dashboard.business.repository.dto.interfaces.IInlineResponse400DTO;
import com.amdocs.digital.ms.coe.dashboard.business.repository.dto.interfaces.ILoginResponseDTO;
import com.amdocs.digital.ms.coe.dashboard.couchbase.dto.AdminDTO;
import com.amdocs.digital.ms.coe.dashboard.couchbase.dto.EmployeeDTO;
import com.amdocs.digital.ms.coe.dashboard.couchbase.dto.InlineResponse400DTO;
import com.amdocs.digital.ms.coe.dashboard.couchbase.dto.LoginResponseDTO;


/**
 * Configuration class for the Repository layer.
 */
@Configuration
public class RepositoriesConfig {
	
	@Bean
	@Scope("prototype")
	public IAdminDTO adminDTO() {
		return new AdminDTO();
	}

	@Bean
	@Scope("prototype")
	public IEmployeeDTO employeeDTO() {
		return new EmployeeDTO();
	}

	@Bean
	@Scope("prototype")
	public IInlineResponse400DTO inlineResponse400DTO() {
		return new InlineResponse400DTO();
	}

	@Bean
	@Scope("prototype")
	public ILoginResponseDTO loginResponseDTO() {
		return new LoginResponseDTO();
	}

}
