//This code was generated by MS-Builder
package com.amdocs.digital.ms.coe.dashboard.resources.delegates;


import org.junit.Test;
import javax.inject.Inject;
import com.amdocs.digital.ms.coe.dashboard.tests.setup.TestSetUp;

import com.amdocs.digital.ms.coe.dashboard.resources.implementation.AdminApiImpl.AdminGetEmpInputGetParameters;
import com.amdocs.digital.ms.coe.dashboard.resources.implementation.AdminApiImpl.IAdminGetEmpInputGetDelegate;
import com.amdocs.msbase.queryparameters.Filter;
import com.amdocs.msbase.queryparameters.PaginationInfo;
import com.amdocs.msbase.queryparameters.SelectedAttributes;
import com.amdocs.msbase.queryparameters.SortFields;


public class AdminGetEmpInputGetDelegateTest extends TestSetUp
{
    @Inject
    protected IAdminGetEmpInputGetDelegate adminGetEmpInputGetDelegate;

    @Test(expected = UnsupportedOperationException.class)
    public void testExecute()
    {
        AdminGetEmpInputGetParameters adminGetEmpInputGetParameters = createAdminGetEmpInputGetParameters();

        //TODO implement test accordingly
        adminGetEmpInputGetDelegate.execute(adminGetEmpInputGetParameters);
    }
	
    private AdminGetEmpInputGetParameters createAdminGetEmpInputGetParameters(){
        AdminGetEmpInputGetParameters adminGetEmpInputGetParameters = new AdminGetEmpInputGetParameters();
        adminGetEmpInputGetParameters.setAuthorization(getDefaultStringValue());
        adminGetEmpInputGetParameters.setInput(getDefaultStringValue());
        return adminGetEmpInputGetParameters;
    }


}