//This code was generated by MS-Builder
package com.amdocs.digital.ms.coe.dashboard.resources.delegates;


import org.junit.Test;
import javax.inject.Inject;
import com.amdocs.digital.ms.coe.dashboard.tests.setup.TestSetUp;

import com.amdocs.digital.ms.coe.dashboard.resources.implementation.AdminApiImpl.AdminGetParameters;
import com.amdocs.digital.ms.coe.dashboard.resources.implementation.AdminApiImpl.IAdminGetDelegate;
import com.amdocs.msbase.queryparameters.Filter;
import com.amdocs.msbase.queryparameters.PaginationInfo;
import com.amdocs.msbase.queryparameters.SelectedAttributes;
import com.amdocs.msbase.queryparameters.SortFields;


public class AdminGetDelegateTest extends TestSetUp
{
    @Inject
    protected IAdminGetDelegate adminGetDelegate;

    @Test(expected = UnsupportedOperationException.class)
    public void testExecute()
    {
        AdminGetParameters adminGetParameters = createAdminGetParameters();

        //TODO implement test accordingly
        adminGetDelegate.execute(adminGetParameters);
    }
	
    private AdminGetParameters createAdminGetParameters(){
        AdminGetParameters adminGetParameters = new AdminGetParameters();
        return adminGetParameters;
    }


}