//This code was generated by MS-Builder
package com.amdocs.digital.ms.coe.dashboard.resources.delegates;


import org.junit.Test;
import javax.inject.Inject;
import com.amdocs.digital.ms.coe.dashboard.tests.setup.TestSetUp;

import com.amdocs.digital.ms.coe.dashboard.resources.implementation.AdminApiImpl.AdminGetSkillsGetParameters;
import com.amdocs.digital.ms.coe.dashboard.resources.implementation.AdminApiImpl.IAdminGetSkillsGetDelegate;
import com.amdocs.msbase.queryparameters.Filter;
import com.amdocs.msbase.queryparameters.PaginationInfo;
import com.amdocs.msbase.queryparameters.SelectedAttributes;
import com.amdocs.msbase.queryparameters.SortFields;


public class AdminGetSkillsGetDelegateTest extends TestSetUp
{
    @Inject
    protected IAdminGetSkillsGetDelegate adminGetSkillsGetDelegate;

    @Test(expected = UnsupportedOperationException.class)
    public void testExecute()
    {
        AdminGetSkillsGetParameters adminGetSkillsGetParameters = createAdminGetSkillsGetParameters();

        //TODO implement test accordingly
        adminGetSkillsGetDelegate.execute(adminGetSkillsGetParameters);
    }
	
    private AdminGetSkillsGetParameters createAdminGetSkillsGetParameters(){
        AdminGetSkillsGetParameters adminGetSkillsGetParameters = new AdminGetSkillsGetParameters();
        adminGetSkillsGetParameters.setAuthorization(getDefaultStringValue());
        return adminGetSkillsGetParameters;
    }


}