//This code was generated by MS-Builder
package com.amdocs.digital.ms.coe.dashboard.resources.delegates;


import org.junit.Test;
import javax.inject.Inject;
import com.amdocs.digital.ms.coe.dashboard.tests.setup.TestSetUp;

import com.amdocs.digital.ms.coe.dashboard.business.repository.dto.interfaces.IAdminDTO;
import com.amdocs.digital.ms.coe.dashboard.resources.implementation.AdminApiImpl.AdminLoginPostParameters;
import com.amdocs.digital.ms.coe.dashboard.resources.implementation.AdminApiImpl.IAdminLoginPostDelegate;
import com.amdocs.digital.ms.coe.dashboard.resources.mappers.interfaces.IMapAdminToAdminDTO;
import com.amdocs.digital.ms.coe.dashboard.resources.models.Admin;
import com.amdocs.msbase.queryparameters.Filter;
import com.amdocs.msbase.queryparameters.PaginationInfo;
import com.amdocs.msbase.queryparameters.SelectedAttributes;
import com.amdocs.msbase.queryparameters.SortFields;


public class AdminLoginPostDelegateTest extends TestSetUp
{
    @Inject
    protected IAdminLoginPostDelegate adminLoginPostDelegate;

    @Test(expected = UnsupportedOperationException.class)
    public void testExecute()
    {
        AdminLoginPostParameters adminLoginPostParameters = createAdminLoginPostParameters();

        //TODO implement test accordingly
        adminLoginPostDelegate.execute(adminLoginPostParameters);
    }
	
    private Admin createAdmin(){
        Admin admin = new Admin();
        admin.setAdminEmail(getDefaultStringValue());
        admin.setAdminPassword(getDefaultStringValue());
        return admin;
    }

    private AdminLoginPostParameters createAdminLoginPostParameters(){
        AdminLoginPostParameters adminLoginPostParameters = new AdminLoginPostParameters();
        adminLoginPostParameters.setAdmin(createAdmin());
        return adminLoginPostParameters;
    }


}