//This code was generated by MS-Builder
package com.amdocs.digital.ms.coe.dashboard.resources.delegates;


import org.junit.Test;
import javax.inject.Inject;
import com.amdocs.digital.ms.coe.dashboard.tests.setup.TestSetUp;

import com.amdocs.digital.ms.coe.dashboard.resources.implementation.AdminApiImpl.AdminGetDomainGetParameters;
import com.amdocs.digital.ms.coe.dashboard.resources.implementation.AdminApiImpl.IAdminGetDomainGetDelegate;
import com.amdocs.msbase.queryparameters.Filter;
import com.amdocs.msbase.queryparameters.PaginationInfo;
import com.amdocs.msbase.queryparameters.SelectedAttributes;
import com.amdocs.msbase.queryparameters.SortFields;


public class AdminGetDomainGetDelegateTest extends TestSetUp
{
    @Inject
    protected IAdminGetDomainGetDelegate adminGetDomainGetDelegate;

    @Test(expected = UnsupportedOperationException.class)
    public void testExecute()
    {
        AdminGetDomainGetParameters adminGetDomainGetParameters = createAdminGetDomainGetParameters();

        //TODO implement test accordingly
        adminGetDomainGetDelegate.execute(adminGetDomainGetParameters);
    }
	
    private AdminGetDomainGetParameters createAdminGetDomainGetParameters(){
        AdminGetDomainGetParameters adminGetDomainGetParameters = new AdminGetDomainGetParameters();
        adminGetDomainGetParameters.setAuthorization(getDefaultStringValue());
        return adminGetDomainGetParameters;
    }


}