//This code was generated by MS-Builder
package com.amdocs.digital.ms.coe.dashboard.resources.delegates;


import org.junit.Test;
import javax.inject.Inject;
import com.amdocs.digital.ms.coe.dashboard.tests.setup.TestSetUp;

import com.amdocs.digital.ms.coe.dashboard.resources.implementation.AdminApiImpl.AdminGetApprovalsGetParameters;
import com.amdocs.digital.ms.coe.dashboard.resources.implementation.AdminApiImpl.IAdminGetApprovalsGetDelegate;
import com.amdocs.msbase.queryparameters.Filter;
import com.amdocs.msbase.queryparameters.PaginationInfo;
import com.amdocs.msbase.queryparameters.SelectedAttributes;
import com.amdocs.msbase.queryparameters.SortFields;


public class AdminGetApprovalsGetDelegateTest extends TestSetUp
{
    @Inject
    protected IAdminGetApprovalsGetDelegate adminGetApprovalsGetDelegate;

    @Test(expected = UnsupportedOperationException.class)
    public void testExecute()
    {
        AdminGetApprovalsGetParameters adminGetApprovalsGetParameters = createAdminGetApprovalsGetParameters();

        //TODO implement test accordingly
        adminGetApprovalsGetDelegate.execute(adminGetApprovalsGetParameters);
    }
	
    private AdminGetApprovalsGetParameters createAdminGetApprovalsGetParameters(){
        AdminGetApprovalsGetParameters adminGetApprovalsGetParameters = new AdminGetApprovalsGetParameters();
        adminGetApprovalsGetParameters.setAuthorization(getDefaultStringValue());
        return adminGetApprovalsGetParameters;
    }


}