//This code was generated by MS-Builder
package com.amdocs.digital.ms.coe.dashboard.resources.delegates;


import org.junit.Test;
import javax.inject.Inject;
import com.amdocs.digital.ms.coe.dashboard.tests.setup.TestSetUp;

import com.amdocs.digital.ms.coe.dashboard.resources.implementation.EmployeeApiImpl.EmployeeGetEmpInputGetParameters;
import com.amdocs.digital.ms.coe.dashboard.resources.implementation.EmployeeApiImpl.IEmployeeGetEmpInputGetDelegate;
import com.amdocs.msbase.queryparameters.Filter;
import com.amdocs.msbase.queryparameters.PaginationInfo;
import com.amdocs.msbase.queryparameters.SelectedAttributes;
import com.amdocs.msbase.queryparameters.SortFields;


public class EmployeeGetEmpInputGetDelegateTest extends TestSetUp
{
    @Inject
    protected IEmployeeGetEmpInputGetDelegate employeeGetEmpInputGetDelegate;

    @Test(expected = UnsupportedOperationException.class)
    public void testExecute()
    {
        EmployeeGetEmpInputGetParameters employeeGetEmpInputGetParameters = createEmployeeGetEmpInputGetParameters();

        //TODO implement test accordingly
        employeeGetEmpInputGetDelegate.execute(employeeGetEmpInputGetParameters);
    }
	
    private EmployeeGetEmpInputGetParameters createEmployeeGetEmpInputGetParameters(){
        EmployeeGetEmpInputGetParameters employeeGetEmpInputGetParameters = new EmployeeGetEmpInputGetParameters();
        employeeGetEmpInputGetParameters.setAuthorization(getDefaultStringValue());
        employeeGetEmpInputGetParameters.setInput(getDefaultStringValue());
        return employeeGetEmpInputGetParameters;
    }


}