//This code was generated by MS-Builder
package com.amdocs.digital.ms.coe.dashboard.resources.delegates;


import org.junit.Test;
import javax.inject.Inject;
import com.amdocs.digital.ms.coe.dashboard.tests.setup.TestSetUp;

import com.amdocs.digital.ms.coe.dashboard.resources.implementation.EmployeeApiImpl.EmployeeGetDomainGetParameters;
import com.amdocs.digital.ms.coe.dashboard.resources.implementation.EmployeeApiImpl.IEmployeeGetDomainGetDelegate;
import com.amdocs.msbase.queryparameters.Filter;
import com.amdocs.msbase.queryparameters.PaginationInfo;
import com.amdocs.msbase.queryparameters.SelectedAttributes;
import com.amdocs.msbase.queryparameters.SortFields;


public class EmployeeGetDomainGetDelegateTest extends TestSetUp
{
    @Inject
    protected IEmployeeGetDomainGetDelegate employeeGetDomainGetDelegate;

    @Test(expected = UnsupportedOperationException.class)
    public void testExecute()
    {
        EmployeeGetDomainGetParameters employeeGetDomainGetParameters = createEmployeeGetDomainGetParameters();

        //TODO implement test accordingly
        employeeGetDomainGetDelegate.execute(employeeGetDomainGetParameters);
    }
	
    private EmployeeGetDomainGetParameters createEmployeeGetDomainGetParameters(){
        EmployeeGetDomainGetParameters employeeGetDomainGetParameters = new EmployeeGetDomainGetParameters();
        return employeeGetDomainGetParameters;
    }


}