//This code was generated by MS-Builder
package com.amdocs.digital.ms.coe.dashboard.resources.delegates;


import org.junit.Test;
import javax.inject.Inject;
import com.amdocs.digital.ms.coe.dashboard.tests.setup.TestSetUp;

import com.amdocs.digital.ms.coe.dashboard.resources.implementation.EmployeeApiImpl.EmployeeGetAllEmpGetParameters;
import com.amdocs.digital.ms.coe.dashboard.resources.implementation.EmployeeApiImpl.IEmployeeGetAllEmpGetDelegate;
import com.amdocs.msbase.queryparameters.Filter;
import com.amdocs.msbase.queryparameters.PaginationInfo;
import com.amdocs.msbase.queryparameters.SelectedAttributes;
import com.amdocs.msbase.queryparameters.SortFields;


public class EmployeeGetAllEmpGetDelegateTest extends TestSetUp
{
    @Inject
    protected IEmployeeGetAllEmpGetDelegate employeeGetAllEmpGetDelegate;

    @Test(expected = UnsupportedOperationException.class)
    public void testExecute()
    {
        EmployeeGetAllEmpGetParameters employeeGetAllEmpGetParameters = createEmployeeGetAllEmpGetParameters();

        //TODO implement test accordingly
        employeeGetAllEmpGetDelegate.execute(employeeGetAllEmpGetParameters);
    }
	
    private EmployeeGetAllEmpGetParameters createEmployeeGetAllEmpGetParameters(){
        EmployeeGetAllEmpGetParameters employeeGetAllEmpGetParameters = new EmployeeGetAllEmpGetParameters();
        employeeGetAllEmpGetParameters.setAuthorization(getDefaultStringValue());
        return employeeGetAllEmpGetParameters;
    }


}