//This code was generated by MS-Builder
package com.amdocs.digital.ms.coe.dashboard.resources.delegates;


import org.junit.Test;
import javax.inject.Inject;
import com.amdocs.digital.ms.coe.dashboard.tests.setup.TestSetUp;

import com.amdocs.digital.ms.coe.dashboard.resources.implementation.EmployeeApiImpl.EmployeeGetByIdIdGetParameters;
import com.amdocs.digital.ms.coe.dashboard.resources.implementation.EmployeeApiImpl.IEmployeeGetByIdIdGetDelegate;
import com.amdocs.msbase.queryparameters.Filter;
import com.amdocs.msbase.queryparameters.PaginationInfo;
import com.amdocs.msbase.queryparameters.SelectedAttributes;
import com.amdocs.msbase.queryparameters.SortFields;


public class EmployeeGetByIdIdGetDelegateTest extends TestSetUp
{
    @Inject
    protected IEmployeeGetByIdIdGetDelegate employeeGetByIdIdGetDelegate;

    @Test(expected = UnsupportedOperationException.class)
    public void testExecute()
    {
        EmployeeGetByIdIdGetParameters employeeGetByIdIdGetParameters = createEmployeeGetByIdIdGetParameters();

        //TODO implement test accordingly
        employeeGetByIdIdGetDelegate.execute(employeeGetByIdIdGetParameters);
    }
	
    private EmployeeGetByIdIdGetParameters createEmployeeGetByIdIdGetParameters(){
        EmployeeGetByIdIdGetParameters employeeGetByIdIdGetParameters = new EmployeeGetByIdIdGetParameters();
        employeeGetByIdIdGetParameters.setAuthorization(getDefaultStringValue());
        employeeGetByIdIdGetParameters.setId(getDefaultStringValue());
        return employeeGetByIdIdGetParameters;
    }


}