---
configFileVersion: 1
msbuilderVersion: "6.9.1"
reportedTemplatesVersion: "23.05.01.01"
cliArguments:
  template: "crud"
  suppress-build: "true"
  name: "coe-dashboard"
  api-file-path: "C:\\Users\\kathanp\\Downloads\\COE-Dashboard Swagger.yaml"
properties:
  codegenExtApiPackage: "com.amdocs.${buName}.ms.${externalMsName}.ck.resources.interfaces"
  codegenPath: "${basePath}/${msName}-ms/${msName}-api/target/${msName}-api-${msVersion}.jar"
  disableConcurrentBuilds: "false"
  csbVersion: "1.2.4"
  settingsSharedLibCredentialsId: "single_ci_new"
  emailList: "someone@amdocs.com"
  resourcesProjectPath: "${basePath}/${msName}-ms/${msName}-resources"
  apiFileArtifactId: ""
  pullSecretImageRegistryServerAddress: "illin5564.corp.amdocs.com:5000"
  dockerProxyEmail: "test@test.com"
  exeProjectPath: "${basePath}/${msName}-ms/${msName}-exe"
  overridePersistenceDTOInterface: "false"
  persistenceProjectPath: "${basePath}/${msName}-ms/${msName}-persistence"
  productName: "ms360"
  artifactDaysToKeepStr: ""
  logFailure: "true"
  settingsSharedLibBranch: "master"
  componentTestProjectPath: "${basePath}/${msName}-ms/${msName}-component-tests"
  templateNexusArtifactName: "ms-builder-templates"
  jenkinsNode: "master"
  codegenImplementationGatewayPackage: "com.amdocs.${buName}.ms.${msName}.resources.implementation"
  overrideMapperInterface: "false"
  codegenModelsPackage: "com.amdocs.${buName}.ms.${msName}.resources.models"
  apiFilePath: ""
  cloudKubernetesName: "kubernetes1"
  overrideMapperImplementation: "false"
  overridePersistenceConfig: "true"
  nexusUser: ""
  testsProjectPath: "${basePath}/${msName}-ms/${msName}-tests"
  dockerA3sConfigJson: "ewoJImF1dGhzIjogewoJCSJpbGxpbjUyMjUuY29ycC5hbWRvY3MuY29tOjUwMDAiOiB7CgkJCSJhdXRoIjogIllUTnpSR1Z3Ykc5NVpYSTZRVE56UkdWd2JHOTVaWEloQ2c9PSIsCgkJCSJzZXJ2aWNldXNlclBhc3N3b3JkIjogIlVuaXgxMSEiCgkJfSwKCQkiaWxsaW41MjI1OjUwMDAiOiB7CgkJCSJhdXRoIjogIllUTnpSR1Z3Ykc5NVpYSTZRVE56UkdWd2JHOTVaWEloQ2c9PSIsCgkJCSJzZXJ2aWNldXNlclBhc3N3b3JkIjogIlVuaXgxMSEiCgkJfSwKCQkiaWxsaW41NTY0LmNvcnAuYW1kb2NzLmNvbTo1MDAwIjogewoJCQkiYXV0aCI6ICJZVE56UkdWd2JHOTVaWEk2UVROelJHVndiRzk1WlhJaENnPT0iLAoJCQkic2VydmljZXVzZXJQYXNzd29yZCI6ICJVbml4MTEhIgoJCX0sCgkJImlsbGluNTU2NDo1MDAwIjogewoJCQkiYXV0aCI6ICJZVE56UkdWd2JHOTVaWEk2UVROelJHVndiRzk1WlhJaENnPT0iLAoJCQkic2VydmljZXVzZXJQYXNzd29yZCI6ICJVbml4MTEhIgoJCX0sCgkJImlsbGluNTU2NC5jb3JwLmFtZG9jcy5jb206NDAwMCI6IHsKCQkJImF1dGgiOiAiWVROelJHVndiRzk1WlhJNlFUTnpSR1Z3Ykc5NVpYSWhDZz09IiwKCQkJInNlcnZpY2V1c2VyUGFzc3dvcmQiOiAiVW5peDExISIKCQl9LAoJCSJpbGxpbjUyMjUuY29ycC5hbWRvY3MuY29tOjcwMDAiOiB7CgkJCSJhdXRoIjogIllUTnpSR1Z3Ykc5NVpYSTZRVE56UkdWd2JHOTVaWEloQ2c9PSIsCgkJCSJzZXJ2aWNldXNlclBhc3N3b3JkIjogIlVuaXgxMSEiCgkJfSwKCQkiaWxsaW41MjI1OjcwMDAiOiB7CgkJCSJhdXRoIjogIllUTnpSR1Z3Ykc5NVpYSTZRVE56UkdWd2JHOTVaWEloQ2c9PSIsCgkJCSJzZXJ2aWNldXNlclBhc3N3b3JkIjogIlVuaXgxMSEiCgkJfQoJfQp9"
  settingsSharedLibRelativeTargetDir: "settings"
  msName: ""
  apiFileGroupId: ""
  thirdPartyNexusAddress: "illin4261.corp.amdocs.com:28080"
  dockerPlatformConfigJson: "ewogICJhdXRocyI6IHsKICAgICJpbGxpbjUyMjUuY29ycC5hbWRvY3MuY29tOjUwMDAiOiB7CiAgICAgICJhdXRoIjogImNITnRaRzlqYTJWeU9uVnVhWGd4TVE9PSIKICAgIH0sCiAgICAiaWxsaW41MjI1OjUwMDAiOiB7CiAgICAgICJhdXRoIjogImNITnRaRzlqYTJWeU9uVnVhWGd4TVE9PSIKICAgIH0sCiAgICAiaWxsaW41NTY0LmNvcnAuYW1kb2NzLmNvbTo1MDAwIjogewogICAgICAiYXV0aCI6ICJjSE50Wkc5amEyVnlPblZ1YVhneE1RPT0iCiAgICB9LAogICAgImlsbGluNTU2NDo1MDAwIjogewogICAgICAiYXV0aCI6ICJjSE50Wkc5amEyVnlPblZ1YVhneE1RPT0iCiAgICB9LAogICAgImlsbGluNTU2NC5jb3JwLmFtZG9jcy5jb206NDAwMCI6IHsKICAgICAgImF1dGgiOiAiY0hOdFpHOWphMlZ5T25WdWFYZ3hNUT09IgogICAgfSwKICAgICJpbGxpbjUyMjUuY29ycC5hbWRvY3MuY29tOjcwMDAiOiB7CiAgICAgICJhdXRoIjogImNIVnNiSFZ6WlhJNmRXNXBlREV4IgogICAgfSwKICAgICJpbGxpbjUyMjU6NzAwMCI6IHsKICAgICAgImF1dGgiOiAiY0hWc2JIVnpaWEk2ZFc1cGVERXgiCiAgICB9CiAgfQp9"
  asyncApiFileVersion: ""
  msVersion: "1.0.0-SNAPSHOT"
  parentProjectPath: "${basePath}/${msName}-ms/${msName}-parent"
  singleCILogLevel: "INFO"
  logSuccess: "true"
  thirdPartyHelmRepo: "PLATFORM_RELEASE_HELM/com/amdocs/platform"
  versionCalculationSshCredentialsId: "single_ci_new"
  swaggerType: ""
  templateVersion: "latest"
  clientKitInterfacePackage: "com.amdocs.${buName}.ms.${msName}.ck.resources.interfaces"
  servicesProjectPath: "${basePath}/${msName}-ms/${msName}-services"
  overridePersistenceEnum: "false"
  amdocsGroupName: "core"
  log: "true"
  helmChartParentTemplate: "root"
  a3sTemplate: "External_a3s-ilde9435_svc.yml"
  ms360ConfigPath: "${basePath}/${msName}-ms"
  numToKeepStr: ""
  milcyVersion: "1.17.4"
  ciParentPath: "ms360-common-ci/ms360-ci/templates/pipeline-config-${template}.yaml"
  templateNexusGroupId: "com.amdocs.digital"
  ciTemplates: ""
  codegenExtModelsPackage: "com.amdocs.${buName}.ms.${externalMsName}.ck.resources.models"
  discardGeneratedLogs: "false"
  singleCIVersion: "1.12.0"
  helmNexusPlatform: "http://illin4261.corp.amdocs.com:28080/repository/PLTO/com/amdocs/platform/ms-lifecycle-operator"
  settingsSharedLibURL: "ssh://git@bitbucket:7999/msb/ms360-settings.git"
  dockerReleaseRegistry: "illin5564.corp.amdocs.com:5000"
  settingsFilePath: "settings/cfg/settings.xml"
  overrideDelegateClasses: "false"
  overrideDelegateConfigClass: "true"
  couchBaseName: "couchbase-service-6"
  helmChartNexusUrl: "http://illin5564.corp.amdocs.com:28080"
  tillerVersion: "v2.14.3"
  couchBaseVersion: "6.6.1"
  overrideDelegateApplicationService: "false"
  kafkaClusterName: "kafka-d1"
  legacyTopics: "true"
  dockerConfigJson: "ew0KICAgICAgICAiYXV0aHMiOiB7DQogICAgICAgICAgICAgICAgImlsbGluNTIyNS5jb3JwLmFtZG9jcy5jb206NTAwMCI6IHsNCiAgICAgICAgICAgICAgICAgICAgICAgICJhdXRoIjogImNITnRaRzlqYTJWeU9uVnVhWGd4TVE9PSINCiAgICAgICAgICAgICAgICB9LA0KICAgICAgICAgICAgICAgICJpbGxpbjUyMjU6NTAwMCI6IHsNCiAgICAgICAgICAgICAgICAgICAgICAgICJhdXRoIjogImNITnRaRzlqYTJWeU9uVnVhWGd4TVE9PSINCiAgICAgICAgICAgICAgICB9LA0KICAgICAgICAgICAgICAgImlsbGluNTU2NC5jb3JwLmFtZG9jcy5jb206NTAwMCI6IHsNCiAgICAgICAgICAgICAgICAgICAgICAgICJhdXRoIjogImNITnRaRzlqYTJWeU9uVnVhWGd4TVE9PSINCiAgICAgICAgICAgICAgICB9LA0KICAgICAgICAgICAgICAgImlsbGluNTU2NDo1MDAwIjogew0KICAgICAgICAgICAgICAgICAgICAgICAgImF1dGgiOiAiY0hOdFpHOWphMlZ5T25WdWFYZ3hNUT09Ig0KICAgICAgICAgICAgICAgIH0NCiAgICAgICAgfQ0KfQ=="
  asyncApiFileGroupId: ""
  defaultPullSecretForJenkinsSlavePod: "ms360-ci-slave-pull-secret"
  clientKitModelPackage: "com.amdocs.${buName}.ms.${msName}.ck.resources.models"
  confluenceParentPageId: "25274042"
  sonarQubeEnvironment: "Sonar"
  helmRepoRelease: "illin5564:28080/repository/helm-release/"
  ciParentTargetDir: "ms360-common-ci"
  dockerHost: ""
  apiFileVersion: ""
  generateDM: "false"
  clientKitResourcePackage: "com.amdocs.${buName}.ms.${msName}.ck.resources"
  overrideServiceDMConfig: "true"
  overrideServiceDMInterface: "false"
  consoleSuccess: "true"
  artifactNumToKeepStr: ""
  nexusRepository: ""
  overrideMapperConfig: "true"
  ciNameSpace: "ci-automation"
  codegenRepositoryDTOPackage: "com.amdocs.${buName}.ms.${msName}.business.repository.dto.interfaces"
  kafkaVersion: "1.4.4"
  codegenImplementationPackage: "com.amdocs.${buName}.ms.${msName}.resources.implementation"
  consoleFailure: "true"
  helmCharStagingtNexusRepoName: ""
  generateSwaggerExamples: "true"
  dockerProxyPlatform: "illin4261.corp.amdocs.com:28090"
  ciInherit: "false"
  overrideDelegateApplicationServiceInterface: "false"
  kubernetesTemplatesRepo: "PSM"
  ciParentUrlCredentialsId: "single_ci_new"
  buName: "digital"
  templateNexusURI: "http://illin5564.corp.amdocs.com:28080/"
  ksbVersion: "1.4.4"
  helmNexusCsb: "http://illin4261.corp.amdocs.com:28080/repository/PLTO/com/amdocs/platform/couchbase-service-broker"
  overridePersistenceDTOImplementation: "false"
  catalogElasticCredentialsId: "single_ms_ci_elastic_credentials"
  helmNexusKsb: "http://illin4261.corp.amdocs.com:28080/repository/PLTO/com/amdocs/platform/kafka-service-broker"
  separateHelmDir: "false"
  msSize: ""
  customPullSecretForJenkinsSlavePod: "nexus-illin5564-5000-pull-secret"
  copySwaggerFileToHelmChart: "true"
  generatePersistence: "true"
  helmChartNexusCredentialsId: "helm_nexus_correct_token"
  dockerProxyPassword: "unix11"
  singleCIUrl: "ssh://git@bitbucket:7999/jco/single-ms-ci-shared-lib.git"
  couchbaseClusterName: "couchbase-service"
  asyncProjectPath: "${basePath}/${msName}-ms/${msName}-asyncmessages"
  nexusAddress: "illin5225.corp.amdocs.com:8081"
  helmInstallationUrl: "http://illin3301.corp.amdocs.com:28080/nexus/content/repositories/PMX-ThirdParty-SW/com/amdocs/internal/helm/v3.5.2-linux-amd64/helm-v3.5.2-linux-amd64.tar.gz"
  gatewaysProjectPath: "${basePath}/${msName}-ms/${msName}-gateways"
  confluenceSpaceKey: "OMM"
  dockerProxyUser: "pulluser"
  singleCICredentialsId: "ms360-ci-private_key"
  zooKeeperVersion: "1.2.6"
  resourceTopics: "true"
  clientKitProjectPath: "${basePath}/${msName}-ms/${msName}-client-kit"
  useLombok: "false"
  overrideServiceDMEnum: "false"
  templateNexusRepoName: "maven-releases"
  pullSecretImageRegistryCredentialsId: "helm_nexus_correct_token"
  helmChartNexusRepoName: "helm-release"
  generateDelegate: "true"
  daysToKeepStr: ""
  codegenPath_services: "${basePath}/${msName}-ms/${msName}-services/target/${msName}-services-${msVersion}.jar"
  runtimePlatform: "ocp"
  debug: "false"
  overrideDelegateapplicationServiceConfig: "true"
  catalogElasticHost: "ilvpbg1938.corp.amdocs.com"
  asyncApiFileArtifactId: ""
  settingsSharedLibDiplayName: "settings.xml"
  moduleLayer: "Core"
  nexusUrl: ""
  basePath: ""
  overrideServiceDMImplementation: "false"
  ciParentUrl: "ssh://git@bitbucket:7999/msb/ms360-common-ci.git"
  generateMapper: "true"
  ciParentBranch: "master"
  podTemplateName: "ms360-maven-slave"
  nexusPass: ""
  apiProjectPath: "${basePath}/${msName}-ms/${msName}-api"
