//This code was generated by MS-Builder
package com.amdocs.digital.ms.coe.dashboard.tests.annotations;

import java.lang.annotation.Documented;
import java.lang.annotation.ElementType;
import java.lang.annotation.Target;

@Documented
@Target({ElementType.METHOD})
public @interface Defect 
{
	String value();
}