//This code was generated by MS-Builder
package com.amdocs.digital.ms.coe.dashboard.business.config;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import com.amdocs.digital.ms.coe.dashboard.business.services.implementation.AdminAddPostApplicationService;
import com.amdocs.digital.ms.coe.dashboard.business.services.implementation.AdminDeleteDeleteApplicationService;
import com.amdocs.digital.ms.coe.dashboard.business.services.implementation.AdminGetApplicationService;
import com.amdocs.digital.ms.coe.dashboard.business.services.implementation.AdminGetAllEmpGetApplicationService;
import com.amdocs.digital.ms.coe.dashboard.business.services.implementation.AdminGetApprovalsGetApplicationService;
import com.amdocs.digital.ms.coe.dashboard.business.services.implementation.AdminGetByIdIdGetApplicationService;
import com.amdocs.digital.ms.coe.dashboard.business.services.implementation.AdminGetDomainGetApplicationService;
import com.amdocs.digital.ms.coe.dashboard.business.services.implementation.AdminGetEmpInputGetApplicationService;
import com.amdocs.digital.ms.coe.dashboard.business.services.implementation.AdminGetSkillsGetApplicationService;
import com.amdocs.digital.ms.coe.dashboard.business.services.implementation.AdminLoginPostApplicationService;
import com.amdocs.digital.ms.coe.dashboard.business.services.implementation.AdminRejectDeleteApplicationService;
import com.amdocs.digital.ms.coe.dashboard.business.services.implementation.AdminUpdatePutApplicationService;
import com.amdocs.digital.ms.coe.dashboard.business.services.implementation.EmployeeForgotPasswordPostApplicationService;
import com.amdocs.digital.ms.coe.dashboard.business.services.implementation.EmployeeGetAllEmpGetApplicationService;
import com.amdocs.digital.ms.coe.dashboard.business.services.implementation.EmployeeGetByIdIdGetApplicationService;
import com.amdocs.digital.ms.coe.dashboard.business.services.implementation.EmployeeGetDomainGetApplicationService;
import com.amdocs.digital.ms.coe.dashboard.business.services.implementation.EmployeeGetEmpInputGetApplicationService;
import com.amdocs.digital.ms.coe.dashboard.business.services.implementation.EmployeeGetSkillsGetApplicationService;
import com.amdocs.digital.ms.coe.dashboard.business.services.implementation.EmployeeLoginPostApplicationService;
import com.amdocs.digital.ms.coe.dashboard.business.services.implementation.EmployeeRegisterPostApplicationService;
import com.amdocs.digital.ms.coe.dashboard.business.services.implementation.EmployeeResetPasswordPostApplicationService;
import com.amdocs.digital.ms.coe.dashboard.business.services.implementation.EmployeeUpdatePutApplicationService;
import com.amdocs.digital.ms.coe.dashboard.business.services.interfaces.IAdminAddPostApplicationService;
import com.amdocs.digital.ms.coe.dashboard.business.services.interfaces.IAdminDeleteDeleteApplicationService;
import com.amdocs.digital.ms.coe.dashboard.business.services.interfaces.IAdminGetApplicationService;
import com.amdocs.digital.ms.coe.dashboard.business.services.interfaces.IAdminGetAllEmpGetApplicationService;
import com.amdocs.digital.ms.coe.dashboard.business.services.interfaces.IAdminGetApprovalsGetApplicationService;
import com.amdocs.digital.ms.coe.dashboard.business.services.interfaces.IAdminGetByIdIdGetApplicationService;
import com.amdocs.digital.ms.coe.dashboard.business.services.interfaces.IAdminGetDomainGetApplicationService;
import com.amdocs.digital.ms.coe.dashboard.business.services.interfaces.IAdminGetEmpInputGetApplicationService;
import com.amdocs.digital.ms.coe.dashboard.business.services.interfaces.IAdminGetSkillsGetApplicationService;
import com.amdocs.digital.ms.coe.dashboard.business.services.interfaces.IAdminLoginPostApplicationService;
import com.amdocs.digital.ms.coe.dashboard.business.services.interfaces.IAdminRejectDeleteApplicationService;
import com.amdocs.digital.ms.coe.dashboard.business.services.interfaces.IAdminUpdatePutApplicationService;
import com.amdocs.digital.ms.coe.dashboard.business.services.interfaces.IEmployeeForgotPasswordPostApplicationService;
import com.amdocs.digital.ms.coe.dashboard.business.services.interfaces.IEmployeeGetAllEmpGetApplicationService;
import com.amdocs.digital.ms.coe.dashboard.business.services.interfaces.IEmployeeGetByIdIdGetApplicationService;
import com.amdocs.digital.ms.coe.dashboard.business.services.interfaces.IEmployeeGetDomainGetApplicationService;
import com.amdocs.digital.ms.coe.dashboard.business.services.interfaces.IEmployeeGetEmpInputGetApplicationService;
import com.amdocs.digital.ms.coe.dashboard.business.services.interfaces.IEmployeeGetSkillsGetApplicationService;
import com.amdocs.digital.ms.coe.dashboard.business.services.interfaces.IEmployeeLoginPostApplicationService;
import com.amdocs.digital.ms.coe.dashboard.business.services.interfaces.IEmployeeRegisterPostApplicationService;
import com.amdocs.digital.ms.coe.dashboard.business.services.interfaces.IEmployeeResetPasswordPostApplicationService;
import com.amdocs.digital.ms.coe.dashboard.business.services.interfaces.IEmployeeUpdatePutApplicationService;
/**
 * Application services configuration file.
 */
@Configuration
public class ApplicationServicesConfig 
{
	@Bean
	public IAdminAddPostApplicationService adminAddPostApplicationService()
	{
		return new AdminAddPostApplicationService();
	}
	
	@Bean
	public IAdminDeleteDeleteApplicationService adminDeleteDeleteApplicationService()
	{
		return new AdminDeleteDeleteApplicationService();
	}
	
	@Bean
	public IAdminGetAllEmpGetApplicationService adminGetAllEmpGetApplicationService()
	{
		return new AdminGetAllEmpGetApplicationService();
	}
	
	@Bean
	public IAdminGetApprovalsGetApplicationService adminGetApprovalsGetApplicationService()
	{
		return new AdminGetApprovalsGetApplicationService();
	}
	
	@Bean
	public IAdminGetByIdIdGetApplicationService adminGetByIdIdGetApplicationService()
	{
		return new AdminGetByIdIdGetApplicationService();
	}
	
	@Bean
	public IAdminGetApplicationService adminGetApplicationService()
	{
		return new AdminGetApplicationService();
	}
	
	@Bean
	public IAdminGetDomainGetApplicationService adminGetDomainGetApplicationService()
	{
		return new AdminGetDomainGetApplicationService();
	}
	
	@Bean
	public IAdminGetEmpInputGetApplicationService adminGetEmpInputGetApplicationService()
	{
		return new AdminGetEmpInputGetApplicationService();
	}
	
	@Bean
	public IAdminGetSkillsGetApplicationService adminGetSkillsGetApplicationService()
	{
		return new AdminGetSkillsGetApplicationService();
	}
	
	@Bean
	public IAdminLoginPostApplicationService adminLoginPostApplicationService()
	{
		return new AdminLoginPostApplicationService();
	}
	
	@Bean
	public IAdminRejectDeleteApplicationService adminRejectDeleteApplicationService()
	{
		return new AdminRejectDeleteApplicationService();
	}
	
	@Bean
	public IAdminUpdatePutApplicationService adminUpdatePutApplicationService()
	{
		return new AdminUpdatePutApplicationService();
	}
	
	@Bean
	public IEmployeeForgotPasswordPostApplicationService employeeForgotPasswordPostApplicationService()
	{
		return new EmployeeForgotPasswordPostApplicationService();
	}
	
	@Bean
	public IEmployeeGetAllEmpGetApplicationService employeeGetAllEmpGetApplicationService()
	{
		return new EmployeeGetAllEmpGetApplicationService();
	}
	
	@Bean
	public IEmployeeGetByIdIdGetApplicationService employeeGetByIdIdGetApplicationService()
	{
		return new EmployeeGetByIdIdGetApplicationService();
	}
	
	@Bean
	public IEmployeeGetDomainGetApplicationService employeeGetDomainGetApplicationService()
	{
		return new EmployeeGetDomainGetApplicationService();
	}
	
	@Bean
	public IEmployeeGetEmpInputGetApplicationService employeeGetEmpInputGetApplicationService()
	{
		return new EmployeeGetEmpInputGetApplicationService();
	}
	
	@Bean
	public IEmployeeGetSkillsGetApplicationService employeeGetSkillsGetApplicationService()
	{
		return new EmployeeGetSkillsGetApplicationService();
	}
	
	@Bean
	public IEmployeeLoginPostApplicationService employeeLoginPostApplicationService()
	{
		return new EmployeeLoginPostApplicationService();
	}
	
	@Bean
	public IEmployeeRegisterPostApplicationService employeeRegisterPostApplicationService()
	{
		return new EmployeeRegisterPostApplicationService();
	}
	
	@Bean
	public IEmployeeResetPasswordPostApplicationService employeeResetPasswordPostApplicationService()
	{
		return new EmployeeResetPasswordPostApplicationService();
	}
	
	@Bean
	public IEmployeeUpdatePutApplicationService employeeUpdatePutApplicationService()
	{
		return new EmployeeUpdatePutApplicationService();
	}
	
}
