//This code was generated by MS-Builder
package com.amdocs.digital.ms.coe.dashboard.business.config;

import org.springframework.context.annotation.Bean; //NOSONAR
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Scope; //NOSONAR

@Configuration
public class DomainServicesConfig 
{
}
