//This code was generated by MS-Builder
package com.amdocs.digital.ms.coe.dashboard.business.services.implementation;

import com.amdocs.digital.ms.coe.dashboard.business.repository.dto.interfaces.IEmployeeDTO;
import com.amdocs.msbase.queryparameters.Filter;
import com.amdocs.msbase.queryparameters.PaginationInfo;
import com.amdocs.msbase.queryparameters.SelectedAttributes;
import com.amdocs.msbase.queryparameters.SortFields;
import java.util.List;

import com.amdocs.digital.ms.coe.dashboard.business.services.interfaces.IAdminGetApprovalsGetApplicationService;

public class AdminGetApprovalsGetApplicationService implements IAdminGetApprovalsGetApplicationService
{
	@Override
	public List<IEmployeeDTO> adminGetApprovalsGet(String authorization, Filter filterConditions, PaginationInfo paginationInfo, SelectedAttributes selectAttributes, SortFields sortFields)
	{
		throw new UnsupportedOperationException("ApplicationService not implemented yet");
	}
}