//This code was generated by MS-Builder
package com.amdocs.digital.ms.coe.dashboard.business.services.implementation;

import com.amdocs.digital.ms.coe.dashboard.business.repository.dto.interfaces.IEmployeeDTO;
import com.amdocs.msbase.queryparameters.Filter;
import com.amdocs.msbase.queryparameters.PaginationInfo;
import com.amdocs.msbase.queryparameters.SelectedAttributes;
import com.amdocs.msbase.queryparameters.SortFields;

import com.amdocs.digital.ms.coe.dashboard.business.services.interfaces.IAdminGetByIdIdGetApplicationService;

public class AdminGetByIdIdGetApplicationService implements IAdminGetByIdIdGetApplicationService
{
	@Override
	public IEmployeeDTO adminGetByIdIdGet(String authorization, Filter filterConditions, String id, PaginationInfo paginationInfo, SelectedAttributes selectAttributes, SortFields sortFields)
	{
		throw new UnsupportedOperationException("ApplicationService not implemented yet");
	}
}