//This code was generated by MS-Builder
package com.amdocs.digital.ms.coe.dashboard.business.services.interfaces;

import com.amdocs.digital.ms.coe.dashboard.business.repository.dto.interfaces.IEmployeeDTO;
import com.amdocs.msbase.queryparameters.Filter;
import com.amdocs.msbase.queryparameters.PaginationInfo;
import com.amdocs.msbase.queryparameters.SelectedAttributes;
import com.amdocs.msbase.queryparameters.SortFields;
import java.util.List;

public interface IEmployeeGetEmpInputGetApplicationService
{
	public List<IEmployeeDTO> employeeGetEmpInputGet(String authorization, Filter filterConditions, String input, PaginationInfo paginationInfo, SelectedAttributes selectAttributes, SortFields sortFields);
}