//This code was generated by MS-Builder
package com.amdocs.digital.ms.coe.dashboard.couchbase.dto;

import com.amdocs.digital.ms.coe.dashboard.business.repository.dto.interfaces.IAdminDTO;

public class AdminDTO implements IAdminDTO
{
	private static final long serialVersionUID = 1L;

	private String adminEmail;
	private String adminPassword;

	public String getAdminEmail()
	{
		return adminEmail;
	}
	public void setAdminEmail(String adminEmail)
	{
		this.adminEmail = adminEmail;
	}

	public String getAdminPassword()
	{
		return adminPassword;
	}
	public void setAdminPassword(String adminPassword)
	{
		this.adminPassword = adminPassword;
	}

}