//This code was generated by MS-Builder
package com.amdocs.digital.ms.coe.dashboard.couchbase.dto;

import com.amdocs.digital.ms.coe.dashboard.business.repository.dto.interfaces.IEmployeeDTO;
import java.util.ArrayList;
import java.util.List;

public class EmployeeDTO implements IEmployeeDTO
{
	private static final long serialVersionUID = 1L;

	private String additionalInfo;
	private String amdocsExperience;
	private String amdocsJourney;
	private Boolean approved;
	private String areaOfCriticalIssue;
	private Boolean contributedToDesign;
	private String currentAccount;
	private String devOpsKnowledge;
	private String empDesc;
	private String empEmail;
	private String empId;
	private String empImage;
	private String empName;
	private String empPassword;
	private String empRole;
	private Boolean engagementActivityContribution;
	private Boolean explorationInterest;
	private List<String> functionalKnowledge = new ArrayList<>();
	private String hobbiesSports;
	private Boolean mentoringAbility;
	private Integer presentationSkills;
	private List<String> primaryProductSubdomain = new ArrayList<>();
	private List<String> primaryTechSkill = new ArrayList<>();
	private String productionSupport;
	private List<String> secondaryProduct = new ArrayList<>();
	private List<String> secondaryTechSkill = new ArrayList<>();
	private String supervisorName;
	private String totalExperience;

	public String getAdditionalInfo()
	{
		return additionalInfo;
	}
	public void setAdditionalInfo(String additionalInfo)
	{
		this.additionalInfo = additionalInfo;
	}

	public String getAmdocsExperience()
	{
		return amdocsExperience;
	}
	public void setAmdocsExperience(String amdocsExperience)
	{
		this.amdocsExperience = amdocsExperience;
	}

	public String getAmdocsJourney()
	{
		return amdocsJourney;
	}
	public void setAmdocsJourney(String amdocsJourney)
	{
		this.amdocsJourney = amdocsJourney;
	}

	public Boolean getApproved()
	{
		return approved;
	}
	public void setApproved(Boolean approved)
	{
		this.approved = approved;
	}

	public String getAreaOfCriticalIssue()
	{
		return areaOfCriticalIssue;
	}
	public void setAreaOfCriticalIssue(String areaOfCriticalIssue)
	{
		this.areaOfCriticalIssue = areaOfCriticalIssue;
	}

	public Boolean getContributedToDesign()
	{
		return contributedToDesign;
	}
	public void setContributedToDesign(Boolean contributedToDesign)
	{
		this.contributedToDesign = contributedToDesign;
	}

	public String getCurrentAccount()
	{
		return currentAccount;
	}
	public void setCurrentAccount(String currentAccount)
	{
		this.currentAccount = currentAccount;
	}

	public String getDevOpsKnowledge()
	{
		return devOpsKnowledge;
	}
	public void setDevOpsKnowledge(String devOpsKnowledge)
	{
		this.devOpsKnowledge = devOpsKnowledge;
	}

	public String getEmpDesc()
	{
		return empDesc;
	}
	public void setEmpDesc(String empDesc)
	{
		this.empDesc = empDesc;
	}

	public String getEmpEmail()
	{
		return empEmail;
	}
	public void setEmpEmail(String empEmail)
	{
		this.empEmail = empEmail;
	}

	public String getEmpId()
	{
		return empId;
	}
	public void setEmpId(String empId)
	{
		this.empId = empId;
	}

	public String getEmpImage()
	{
		return empImage;
	}
	public void setEmpImage(String empImage)
	{
		this.empImage = empImage;
	}

	public String getEmpName()
	{
		return empName;
	}
	public void setEmpName(String empName)
	{
		this.empName = empName;
	}

	public String getEmpPassword()
	{
		return empPassword;
	}
	public void setEmpPassword(String empPassword)
	{
		this.empPassword = empPassword;
	}

	public String getEmpRole()
	{
		return empRole;
	}
	public void setEmpRole(String empRole)
	{
		this.empRole = empRole;
	}

	public Boolean getEngagementActivityContribution()
	{
		return engagementActivityContribution;
	}
	public void setEngagementActivityContribution(Boolean engagementActivityContribution)
	{
		this.engagementActivityContribution = engagementActivityContribution;
	}

	public Boolean getExplorationInterest()
	{
		return explorationInterest;
	}
	public void setExplorationInterest(Boolean explorationInterest)
	{
		this.explorationInterest = explorationInterest;
	}

	@SuppressWarnings("squid:S2384")
	public List<String> getFunctionalKnowledge()
	{
		return functionalKnowledge;
	}
	@SuppressWarnings("squid:S2384")
	public void setFunctionalKnowledge(List<String> functionalKnowledge)
	{
		this.functionalKnowledge = functionalKnowledge;
	}

	public String getHobbiesSports()
	{
		return hobbiesSports;
	}
	public void setHobbiesSports(String hobbiesSports)
	{
		this.hobbiesSports = hobbiesSports;
	}

	public Boolean getMentoringAbility()
	{
		return mentoringAbility;
	}
	public void setMentoringAbility(Boolean mentoringAbility)
	{
		this.mentoringAbility = mentoringAbility;
	}

	public Integer getPresentationSkills()
	{
		return presentationSkills;
	}
	public void setPresentationSkills(Integer presentationSkills)
	{
		this.presentationSkills = presentationSkills;
	}

	@SuppressWarnings("squid:S2384")
	public List<String> getPrimaryProductSubdomain()
	{
		return primaryProductSubdomain;
	}
	@SuppressWarnings("squid:S2384")
	public void setPrimaryProductSubdomain(List<String> primaryProductSubdomain)
	{
		this.primaryProductSubdomain = primaryProductSubdomain;
	}

	@SuppressWarnings("squid:S2384")
	public List<String> getPrimaryTechSkill()
	{
		return primaryTechSkill;
	}
	@SuppressWarnings("squid:S2384")
	public void setPrimaryTechSkill(List<String> primaryTechSkill)
	{
		this.primaryTechSkill = primaryTechSkill;
	}

	public String getProductionSupport()
	{
		return productionSupport;
	}
	public void setProductionSupport(String productionSupport)
	{
		this.productionSupport = productionSupport;
	}

	@SuppressWarnings("squid:S2384")
	public List<String> getSecondaryProduct()
	{
		return secondaryProduct;
	}
	@SuppressWarnings("squid:S2384")
	public void setSecondaryProduct(List<String> secondaryProduct)
	{
		this.secondaryProduct = secondaryProduct;
	}

	@SuppressWarnings("squid:S2384")
	public List<String> getSecondaryTechSkill()
	{
		return secondaryTechSkill;
	}
	@SuppressWarnings("squid:S2384")
	public void setSecondaryTechSkill(List<String> secondaryTechSkill)
	{
		this.secondaryTechSkill = secondaryTechSkill;
	}

	public String getSupervisorName()
	{
		return supervisorName;
	}
	public void setSupervisorName(String supervisorName)
	{
		this.supervisorName = supervisorName;
	}

	public String getTotalExperience()
	{
		return totalExperience;
	}
	public void setTotalExperience(String totalExperience)
	{
		this.totalExperience = totalExperience;
	}

}