//This code was generated by MS-Builder
package com.amdocs.digital.ms.coe.dashboard.couchbase.dto;

import com.amdocs.digital.ms.coe.dashboard.business.repository.dto.interfaces.IInlineResponse400DTO;

public class InlineResponse400DTO implements IInlineResponse400DTO
{
	private static final long serialVersionUID = 1L;

	@SuppressWarnings("squid:S1948")
	private Object employee;

	public Object getEmployee()
	{
		return employee;
	}
	public void setEmployee(Object employee)
	{
		this.employee = employee;
	}

}