//This code was generated by MS-Builder
package com.amdocs.digital.ms.coe.dashboard.couchbase.dto;

import com.amdocs.digital.ms.coe.dashboard.business.repository.dto.interfaces.IEmployeeDTO;
import com.amdocs.digital.ms.coe.dashboard.business.repository.dto.interfaces.ILoginResponseDTO;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

public class LoginResponseDTO implements ILoginResponseDTO
{
	private static final long serialVersionUID = 1L;

	@JsonDeserialize(as = EmployeeDTO.class)
	private IEmployeeDTO employee;
	private String token;

	public IEmployeeDTO getEmployee()
	{
		return employee;
	}
	public void setEmployee(IEmployeeDTO employee)
	{
		this.employee = employee;
	}

	public String getToken()
	{
		return token;
	}
	public void setToken(String token)
	{
		this.token = token;
	}

}