//This code was generated by MS-Builder
package com.amdocs.digital.ms.coe.dashboard.business.constants;

public class Constants
{
    private Constants() {}

    public static final String CB_PROVIDER_BEAN_NAME = "cbProvider";
    public static final String ENTITY_NAME = "entityName";
    public static final String ENTITY_KEY = "entityKey";
    public static final String SERVICE_NAME = "serviceName";
    public static final String ERR_MSG = "errorMsg";
    public static final String VALIDATION_FAILURE_MESSAGES = "validationFailureMessage";
    public static final String SYSTEM_NAME = "systemName";

	public static final String X_TOTAL_COUNT="X-Total-Count";
	public static final String X_TOTAL_PAGES="X-Pagination-Total-Pages";
}
