//This code was generated by MS-Builder
package com.amdocs.digital.ms.coe.dashboard.tests.setup;

import java.util.HashMap;

import org.junit.Before;
import org.springframework.boot.test.mock.mockito.MockBean;

import com.amdocs.msbase.persistence.couchbase.ICouchbaseDTOProvider;
import com.amdocs.msbase.persistence.couchbase.repository.dto.IBaseCouchbaseDTO;
import com.amdocs.msb.repository.interfaces.dataconsistency.IDataConsistencyEventsProvider;

public abstract class ExtendedTestSetUp extends TestSetUp {
	
    @MockBean
    protected IDataConsistencyEventsProvider dataConsistencyEventsProvider;
    
    @MockBean
    protected ICouchbaseDTOProvider couchbaseMock;

    public HashMap<String, IBaseCouchbaseDTO> mockMap = new HashMap<>();


    @Before
    public void setUp() 
    {
        CouchbaseProviderMock.setup(couchbaseMock, mockMap, messages);
    }

}
