//This code was generated by MS-Builder
package com.amdocs.digital.ms.coe.dashboard.tests.setup;

import org.mockito.Mockito;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.PropertySource;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Primary;
import org.springframework.security.authentication.AuthenticationManager;

import com.amdocs.msbase.idempotency.config.IdempotencyConfig;

//import com.amdocs.msnext.securityjwt.ExternalURLProvider;
//import com.amdocs.msnext.securityjwt.ExternalUrlProviderConfiguration;
import com.amdocs.msnext.securityjwt.impl.AutoConfiguration;
import com.amdocs.msnext.securityjwt.impl.AutoConfigurationAddOns;

@SpringBootApplication(exclude = {
        AutoConfiguration.class,
        AutoConfigurationAddOns.class,
        IdempotencyConfig.class
})
@PropertySource("classpath:core-coe-dashboard-config.yaml")
public class TestConfig 
{	

    @Bean
    @Primary
    AuthenticationManager authenticationManager() {
        return Mockito.mock(AuthenticationManager.class);
    }

	//@Bean
	//public ExternalURLProvider externalUrlProvider(ExternalUrlProviderConfiguration externalUrlProviderConfiguration) 
	//{
	//	return new ExternalURLProvider(externalUrlProviderConfiguration);
	//}
}
