//This code was generated by MS-Builder
package com.amdocs.digital.ms.coe.dashboard.resources.mappers.interfaces;

import com.amdocs.digital.ms.coe.dashboard.business.repository.dto.interfaces.ILoginResponseDTO;
import com.amdocs.digital.ms.coe.dashboard.resources.models.LoginResponse;

public interface IMapLoginResponseDTOToLoginResponse
{
	public LoginResponse map(ILoginResponseDTO iLoginResponseDTO);
}