//This code was generated by MS-Builder
package com.amdocs.digital.ms.coe.dashboard.resources.mappers.interfaces;

import com.amdocs.digital.ms.coe.dashboard.business.repository.dto.interfaces.IInlineResponse400DTO;
import com.amdocs.digital.ms.coe.dashboard.resources.models.InlineResponse400;

public interface IMapInlineResponse400ToInlineResponse400DTO
{
	public IInlineResponse400DTO map(InlineResponse400 inlineResponse400);
}