//This code was generated by MS-Builder
package com.amdocs.digital.ms.coe.dashboard.resources.mappers.interfaces;

import com.amdocs.digital.ms.coe.dashboard.business.repository.dto.interfaces.IAdminDTO;
import com.amdocs.digital.ms.coe.dashboard.resources.models.Admin;

public interface IMapAdminToAdminDTO
{
	public IAdminDTO map(Admin admin);
}