//This code was generated by MS-Builder
package com.amdocs.digital.ms.coe.dashboard.resources.mappers.interfaces;

import com.amdocs.digital.ms.coe.dashboard.business.repository.dto.interfaces.IEmployeeDTO;
import com.amdocs.digital.ms.coe.dashboard.resources.models.Employee;

public interface IMapEmployeeToEmployeeDTO
{
	public IEmployeeDTO map(Employee employee);
}