//This code was generated by MS-Builder
package com.amdocs.digital.ms.coe.dashboard.resources.mappers.implementation;

import com.amdocs.digital.ms.coe.dashboard.business.repository.dto.interfaces.IAdminDTO;
import com.amdocs.digital.ms.coe.dashboard.resources.mappers.interfaces.IMapAdminToAdminDTO;
import com.amdocs.digital.ms.coe.dashboard.resources.models.Admin;
import javax.inject.Inject;
import javax.inject.Provider;

public class MapAdminToAdminDTO implements IMapAdminToAdminDTO
{
	@Inject
	private Provider<IAdminDTO> iAdminDTOProvider;

	@Override
	public IAdminDTO map(Admin admin)
	{
		if(null == admin) {
			return null;
		}

		IAdminDTO iAdminDTO = iAdminDTOProvider.get();
		iAdminDTO.setAdminEmail(admin.getAdminEmail());
		iAdminDTO.setAdminPassword(admin.getAdminPassword());

		return iAdminDTO;
	}
}