//This code was generated by MS-Builder
package com.amdocs.digital.ms.coe.dashboard.resources.mappers.implementation;

import com.amdocs.digital.ms.coe.dashboard.business.repository.dto.interfaces.IAdminDTO;
import com.amdocs.digital.ms.coe.dashboard.resources.mappers.interfaces.IMapAdminDTOToAdmin;
import com.amdocs.digital.ms.coe.dashboard.resources.models.Admin;

public class MapAdminDTOToAdmin implements IMapAdminDTOToAdmin
{
	@Override
	public Admin map(IAdminDTO iAdminDTO)
	{
		if(null == iAdminDTO) {
			return null;
		}

		Admin admin = new Admin();
		admin.setAdminEmail(iAdminDTO.getAdminEmail());
		admin.setAdminPassword(iAdminDTO.getAdminPassword());

		return admin;
	}
}