//This code was generated by MS-Builder
package com.amdocs.digital.ms.coe.dashboard.resources.mappers.implementation;

import com.amdocs.digital.ms.coe.dashboard.business.repository.dto.interfaces.IInlineResponse400DTO;
import com.amdocs.digital.ms.coe.dashboard.resources.mappers.interfaces.IMapInlineResponse400ToInlineResponse400DTO;
import com.amdocs.digital.ms.coe.dashboard.resources.models.InlineResponse400;
import javax.inject.Inject;
import javax.inject.Provider;

public class MapInlineResponse400ToInlineResponse400DTO implements IMapInlineResponse400ToInlineResponse400DTO
{
	@Inject
	private Provider<IInlineResponse400DTO> iInlineResponse400DTOProvider;

	@Override
	public IInlineResponse400DTO map(InlineResponse400 inlineResponse400)
	{
		if(null == inlineResponse400) {
			return null;
		}

		IInlineResponse400DTO iInlineResponse400DTO = iInlineResponse400DTOProvider.get();
		iInlineResponse400DTO.setEmployee(inlineResponse400.getEmployee());

		return iInlineResponse400DTO;
	}
}