//This code was generated by MS-Builder
package com.amdocs.digital.ms.coe.dashboard.resources.mappers.implementation;

import com.amdocs.digital.ms.coe.dashboard.business.repository.dto.interfaces.ILoginResponseDTO;
import com.amdocs.digital.ms.coe.dashboard.resources.mappers.interfaces.IMapEmployeeDTOToEmployee;
import com.amdocs.digital.ms.coe.dashboard.resources.mappers.interfaces.IMapLoginResponseDTOToLoginResponse;
import com.amdocs.digital.ms.coe.dashboard.resources.models.LoginResponse;
import javax.inject.Inject;

public class MapLoginResponseDTOToLoginResponse implements IMapLoginResponseDTOToLoginResponse
{
	@Inject
	private IMapEmployeeDTOToEmployee mapEmployeeDTOToEmployee;

	@Override
	public LoginResponse map(ILoginResponseDTO iLoginResponseDTO)
	{
		if(null == iLoginResponseDTO) {
			return null;
		}

		LoginResponse loginResponse = new LoginResponse();
		loginResponse.setEmployee(mapEmployeeDTOToEmployee.map(iLoginResponseDTO.getEmployee()));
		loginResponse.setToken(iLoginResponseDTO.getToken());

		return loginResponse;
	}
}