//This code was generated by MS-Builder
package com.amdocs.digital.ms.coe.dashboard.resources.mappers.implementation;

import com.amdocs.digital.ms.coe.dashboard.business.repository.dto.interfaces.ILoginResponseDTO;
import com.amdocs.digital.ms.coe.dashboard.resources.mappers.interfaces.IMapEmployeeToEmployeeDTO;
import com.amdocs.digital.ms.coe.dashboard.resources.mappers.interfaces.IMapLoginResponseToLoginResponseDTO;
import com.amdocs.digital.ms.coe.dashboard.resources.models.LoginResponse;
import javax.inject.Inject;
import javax.inject.Provider;

public class MapLoginResponseToLoginResponseDTO implements IMapLoginResponseToLoginResponseDTO
{
	@Inject
	private Provider<ILoginResponseDTO> iLoginResponseDTOProvider;

	@Inject
	private IMapEmployeeToEmployeeDTO mapEmployeeToEmployeeDTO;

	@Override
	public ILoginResponseDTO map(LoginResponse loginResponse)
	{
		if(null == loginResponse) {
			return null;
		}

		ILoginResponseDTO iLoginResponseDTO = iLoginResponseDTOProvider.get();
		iLoginResponseDTO.setEmployee(mapEmployeeToEmployeeDTO.map(loginResponse.getEmployee()));
		iLoginResponseDTO.setToken(loginResponse.getToken());

		return iLoginResponseDTO;
	}
}