//This code was generated by MS-Builder
package com.amdocs.digital.ms.coe.dashboard.resources.mappers;

import static org.junit.Assert.assertEquals;
import org.junit.Test;
import javax.inject.Inject;
import com.amdocs.digital.ms.coe.dashboard.tests.setup.TestSetUp;

import com.amdocs.digital.ms.coe.dashboard.resources.mappers.interfaces.IMapAdminToAdminDTO;
import com.amdocs.digital.ms.coe.dashboard.resources.mappers.interfaces.IMapAdminDTOToAdmin;

import com.amdocs.digital.ms.coe.dashboard.business.repository.dto.interfaces.IAdminDTO;
import com.amdocs.digital.ms.coe.dashboard.resources.models.Admin;

public class AdminAdminDTOBidirectionalMapperTest extends TestSetUp
{
    @Inject
    protected IMapAdminToAdminDTO iMapAdminToAdminDTO;

    @Inject
    protected IMapAdminDTOToAdmin iMapAdminDTOToAdmin;

    @Test
    public void testAdminAdminDTOMapper()
    {
        Admin admin = createAdmin();
      
        IAdminDTO adminDTO = iMapAdminToAdminDTO.map(admin);
        Admin adminMapped = iMapAdminDTOToAdmin.map(adminDTO);  
        assertEquals(admin,adminMapped);
    }
    
    private Admin createAdmin(){
        Admin admin = new Admin();
        admin.setAdminEmail(getDefaultStringValue());
        admin.setAdminPassword(getDefaultStringValue());
        return admin;
    }

    
}