//This code was generated by MS-Builder
package com.amdocs.digital.ms.coe.dashboard.resources.config;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import com.amdocs.digital.ms.coe.dashboard.resources.delegates.AdminAddPostDelegate;
import com.amdocs.digital.ms.coe.dashboard.resources.delegates.AdminDeleteDeleteDelegate;
import com.amdocs.digital.ms.coe.dashboard.resources.delegates.AdminGetDelegate;
import com.amdocs.digital.ms.coe.dashboard.resources.delegates.AdminGetAllEmpGetDelegate;
import com.amdocs.digital.ms.coe.dashboard.resources.delegates.AdminGetApprovalsGetDelegate;
import com.amdocs.digital.ms.coe.dashboard.resources.delegates.AdminGetByIdIdGetDelegate;
import com.amdocs.digital.ms.coe.dashboard.resources.delegates.AdminGetDomainGetDelegate;
import com.amdocs.digital.ms.coe.dashboard.resources.delegates.AdminGetEmpInputGetDelegate;
import com.amdocs.digital.ms.coe.dashboard.resources.delegates.AdminGetSkillsGetDelegate;
import com.amdocs.digital.ms.coe.dashboard.resources.delegates.AdminLoginPostDelegate;
import com.amdocs.digital.ms.coe.dashboard.resources.delegates.AdminRejectDeleteDelegate;
import com.amdocs.digital.ms.coe.dashboard.resources.delegates.AdminUpdatePutDelegate;
import com.amdocs.digital.ms.coe.dashboard.resources.delegates.EmployeeForgotPasswordPostDelegate;
import com.amdocs.digital.ms.coe.dashboard.resources.delegates.EmployeeGetAllEmpGetDelegate;
import com.amdocs.digital.ms.coe.dashboard.resources.delegates.EmployeeGetByIdIdGetDelegate;
import com.amdocs.digital.ms.coe.dashboard.resources.delegates.EmployeeGetDomainGetDelegate;
import com.amdocs.digital.ms.coe.dashboard.resources.delegates.EmployeeGetEmpInputGetDelegate;
import com.amdocs.digital.ms.coe.dashboard.resources.delegates.EmployeeGetSkillsGetDelegate;
import com.amdocs.digital.ms.coe.dashboard.resources.delegates.EmployeeLoginPostDelegate;
import com.amdocs.digital.ms.coe.dashboard.resources.delegates.EmployeeRegisterPostDelegate;
import com.amdocs.digital.ms.coe.dashboard.resources.delegates.EmployeeResetPasswordPostDelegate;
import com.amdocs.digital.ms.coe.dashboard.resources.delegates.EmployeeUpdatePutDelegate;
import com.amdocs.digital.ms.coe.dashboard.resources.implementation.AdminApiImpl.IAdminAddPostDelegate;
import com.amdocs.digital.ms.coe.dashboard.resources.implementation.AdminApiImpl.IAdminDeleteDeleteDelegate;
import com.amdocs.digital.ms.coe.dashboard.resources.implementation.AdminApiImpl.IAdminGetAllEmpGetDelegate;
import com.amdocs.digital.ms.coe.dashboard.resources.implementation.AdminApiImpl.IAdminGetApprovalsGetDelegate;
import com.amdocs.digital.ms.coe.dashboard.resources.implementation.AdminApiImpl.IAdminGetByIdIdGetDelegate;
import com.amdocs.digital.ms.coe.dashboard.resources.implementation.AdminApiImpl.IAdminGetDelegate;
import com.amdocs.digital.ms.coe.dashboard.resources.implementation.AdminApiImpl.IAdminGetDomainGetDelegate;
import com.amdocs.digital.ms.coe.dashboard.resources.implementation.AdminApiImpl.IAdminGetEmpInputGetDelegate;
import com.amdocs.digital.ms.coe.dashboard.resources.implementation.AdminApiImpl.IAdminGetSkillsGetDelegate;
import com.amdocs.digital.ms.coe.dashboard.resources.implementation.AdminApiImpl.IAdminLoginPostDelegate;
import com.amdocs.digital.ms.coe.dashboard.resources.implementation.AdminApiImpl.IAdminRejectDeleteDelegate;
import com.amdocs.digital.ms.coe.dashboard.resources.implementation.AdminApiImpl.IAdminUpdatePutDelegate;
import com.amdocs.digital.ms.coe.dashboard.resources.implementation.EmployeeApiImpl.IEmployeeForgotPasswordPostDelegate;
import com.amdocs.digital.ms.coe.dashboard.resources.implementation.EmployeeApiImpl.IEmployeeGetAllEmpGetDelegate;
import com.amdocs.digital.ms.coe.dashboard.resources.implementation.EmployeeApiImpl.IEmployeeGetByIdIdGetDelegate;
import com.amdocs.digital.ms.coe.dashboard.resources.implementation.EmployeeApiImpl.IEmployeeGetDomainGetDelegate;
import com.amdocs.digital.ms.coe.dashboard.resources.implementation.EmployeeApiImpl.IEmployeeGetEmpInputGetDelegate;
import com.amdocs.digital.ms.coe.dashboard.resources.implementation.EmployeeApiImpl.IEmployeeGetSkillsGetDelegate;
import com.amdocs.digital.ms.coe.dashboard.resources.implementation.EmployeeApiImpl.IEmployeeLoginPostDelegate;
import com.amdocs.digital.ms.coe.dashboard.resources.implementation.EmployeeApiImpl.IEmployeeRegisterPostDelegate;
import com.amdocs.digital.ms.coe.dashboard.resources.implementation.EmployeeApiImpl.IEmployeeResetPasswordPostDelegate;
import com.amdocs.digital.ms.coe.dashboard.resources.implementation.EmployeeApiImpl.IEmployeeUpdatePutDelegate;

/**
 * Delegates configuration file.
 */
@Configuration
public class ResourceLayerConfig
{
	@Bean
	public IAdminAddPostDelegate adminAddPostDelegate()
	{
		return new AdminAddPostDelegate();
	}

	@Bean
	public IAdminDeleteDeleteDelegate adminDeleteDeleteDelegate()
	{
		return new AdminDeleteDeleteDelegate();
	}

	@Bean
	public IAdminGetAllEmpGetDelegate adminGetAllEmpGetDelegate()
	{
		return new AdminGetAllEmpGetDelegate();
	}

	@Bean
	public IAdminGetApprovalsGetDelegate adminGetApprovalsGetDelegate()
	{
		return new AdminGetApprovalsGetDelegate();
	}

	@Bean
	public IAdminGetByIdIdGetDelegate adminGetByIdIdGetDelegate()
	{
		return new AdminGetByIdIdGetDelegate();
	}

	@Bean
	public IAdminGetDelegate adminGetDelegate()
	{
		return new AdminGetDelegate();
	}

	@Bean
	public IAdminGetDomainGetDelegate adminGetDomainGetDelegate()
	{
		return new AdminGetDomainGetDelegate();
	}

	@Bean
	public IAdminGetEmpInputGetDelegate adminGetEmpInputGetDelegate()
	{
		return new AdminGetEmpInputGetDelegate();
	}

	@Bean
	public IAdminGetSkillsGetDelegate adminGetSkillsGetDelegate()
	{
		return new AdminGetSkillsGetDelegate();
	}

	@Bean
	public IAdminLoginPostDelegate adminLoginPostDelegate()
	{
		return new AdminLoginPostDelegate();
	}

	@Bean
	public IAdminRejectDeleteDelegate adminRejectDeleteDelegate()
	{
		return new AdminRejectDeleteDelegate();
	}

	@Bean
	public IAdminUpdatePutDelegate adminUpdatePutDelegate()
	{
		return new AdminUpdatePutDelegate();
	}

	@Bean
	public IEmployeeForgotPasswordPostDelegate employeeForgotPasswordPostDelegate()
	{
		return new EmployeeForgotPasswordPostDelegate();
	}

	@Bean
	public IEmployeeGetAllEmpGetDelegate employeeGetAllEmpGetDelegate()
	{
		return new EmployeeGetAllEmpGetDelegate();
	}

	@Bean
	public IEmployeeGetByIdIdGetDelegate employeeGetByIdIdGetDelegate()
	{
		return new EmployeeGetByIdIdGetDelegate();
	}

	@Bean
	public IEmployeeGetDomainGetDelegate employeeGetDomainGetDelegate()
	{
		return new EmployeeGetDomainGetDelegate();
	}

	@Bean
	public IEmployeeGetEmpInputGetDelegate employeeGetEmpInputGetDelegate()
	{
		return new EmployeeGetEmpInputGetDelegate();
	}

	@Bean
	public IEmployeeGetSkillsGetDelegate employeeGetSkillsGetDelegate()
	{
		return new EmployeeGetSkillsGetDelegate();
	}

	@Bean
	public IEmployeeLoginPostDelegate employeeLoginPostDelegate()
	{
		return new EmployeeLoginPostDelegate();
	}

	@Bean
	public IEmployeeRegisterPostDelegate employeeRegisterPostDelegate()
	{
		return new EmployeeRegisterPostDelegate();
	}

	@Bean
	public IEmployeeResetPasswordPostDelegate employeeResetPasswordPostDelegate()
	{
		return new EmployeeResetPasswordPostDelegate();
	}

	@Bean
	public IEmployeeUpdatePutDelegate employeeUpdatePutDelegate()
	{
		return new EmployeeUpdatePutDelegate();
	}

}
