//This code was generated by MS-Builder
package com.amdocs.digital.ms.coe.dashboard.resources.delegates;

import javax.inject.Inject;

import com.amdocs.digital.ms.coe.dashboard.business.services.interfaces.IAdminGetDomainGetApplicationService;
import com.amdocs.digital.ms.coe.dashboard.resources.implementation.AdminApiImpl.AdminGetDomainGetParameters;
import com.amdocs.digital.ms.coe.dashboard.resources.implementation.AdminApiImpl.IAdminGetDomainGetDelegate;
import com.amdocs.msbase.queryparameters.Filter;
import com.amdocs.msbase.queryparameters.PaginationInfo;
import com.amdocs.msbase.queryparameters.SelectedAttributes;
import com.amdocs.msbase.queryparameters.SortFields;
import java.util.List;
import org.springframework.http.ResponseEntity;

public class AdminGetDomainGetDelegate implements IAdminGetDomainGetDelegate
{
	@Inject
	protected IAdminGetDomainGetApplicationService adminGetDomainGetApplicationService;

	@Override
	public ResponseEntity<List<String>> execute(AdminGetDomainGetParameters parameters)
	{
		String authorization = parameters.getAuthorization();
		Filter filterConditions = parameters.getFilterConditions();
		PaginationInfo paginationInfo = parameters.getPaginationInfo();
		SelectedAttributes selectAttributes = parameters.getSelectAttributes();
		SortFields sortFields = parameters.getSortFields();

		List<String> response = adminGetDomainGetApplicationService.adminGetDomainGet(authorization, filterConditions, paginationInfo, selectAttributes, sortFields);
		return ResponseEntity.ok(response);
	}
}