//This code was generated by MS-Builder
package com.amdocs.digital.ms.coe.dashboard.resources.delegates;

import javax.inject.Inject;

import com.amdocs.digital.ms.coe.dashboard.business.repository.dto.interfaces.IAdminDTO;
import com.amdocs.digital.ms.coe.dashboard.business.services.interfaces.IAdminLoginPostApplicationService;
import com.amdocs.digital.ms.coe.dashboard.resources.implementation.AdminApiImpl.AdminLoginPostParameters;
import com.amdocs.digital.ms.coe.dashboard.resources.implementation.AdminApiImpl.IAdminLoginPostDelegate;
import com.amdocs.digital.ms.coe.dashboard.resources.mappers.interfaces.IMapAdminToAdminDTO;
import com.amdocs.digital.ms.coe.dashboard.resources.models.Admin;
import com.amdocs.msbase.queryparameters.Filter;
import com.amdocs.msbase.queryparameters.PaginationInfo;
import com.amdocs.msbase.queryparameters.SelectedAttributes;
import com.amdocs.msbase.queryparameters.SortFields;
import org.springframework.http.ResponseEntity;

public class AdminLoginPostDelegate implements IAdminLoginPostDelegate
{
	@Inject
	protected IMapAdminToAdminDTO mapAdminToAdminDTO;

	@Inject
	protected IAdminLoginPostApplicationService adminLoginPostApplicationService;

	@Override
	public ResponseEntity<String> execute(AdminLoginPostParameters parameters)
	{
		Admin admin = parameters.getAdmin();

		IAdminDTO requestAdminDTO = mapAdminToAdminDTO.map(admin);
		Filter filterConditions = parameters.getFilterConditions();
		PaginationInfo paginationInfo = parameters.getPaginationInfo();
		SelectedAttributes selectAttributes = parameters.getSelectAttributes();
		SortFields sortFields = parameters.getSortFields();

		String response = adminLoginPostApplicationService.adminLoginPost(requestAdminDTO, filterConditions, paginationInfo, selectAttributes, sortFields);
		return ResponseEntity.ok(response);
	}
}