//This code was generated by MS-Builder
package com.amdocs.digital.ms.coe.dashboard.resources.delegates;

import javax.inject.Inject;

import com.amdocs.digital.ms.coe.dashboard.business.services.interfaces.IAdminGetSkillsGetApplicationService;
import com.amdocs.digital.ms.coe.dashboard.resources.implementation.AdminApiImpl.AdminGetSkillsGetParameters;
import com.amdocs.digital.ms.coe.dashboard.resources.implementation.AdminApiImpl.IAdminGetSkillsGetDelegate;
import com.amdocs.msbase.queryparameters.Filter;
import com.amdocs.msbase.queryparameters.PaginationInfo;
import com.amdocs.msbase.queryparameters.SelectedAttributes;
import com.amdocs.msbase.queryparameters.SortFields;
import java.util.List;
import org.springframework.http.ResponseEntity;

public class AdminGetSkillsGetDelegate implements IAdminGetSkillsGetDelegate
{
	@Inject
	protected IAdminGetSkillsGetApplicationService adminGetSkillsGetApplicationService;

	@Override
	public ResponseEntity<List<String>> execute(AdminGetSkillsGetParameters parameters)
	{
		String authorization = parameters.getAuthorization();
		Filter filterConditions = parameters.getFilterConditions();
		PaginationInfo paginationInfo = parameters.getPaginationInfo();
		SelectedAttributes selectAttributes = parameters.getSelectAttributes();
		SortFields sortFields = parameters.getSortFields();

		List<String> response = adminGetSkillsGetApplicationService.adminGetSkillsGet(authorization, filterConditions, paginationInfo, selectAttributes, sortFields);
		return ResponseEntity.ok(response);
	}
}