//This code was generated by MS-Builder
package com.amdocs.digital.ms.coe.dashboard.resources.delegates;

import javax.inject.Inject;

import com.amdocs.digital.ms.coe.dashboard.business.services.interfaces.IEmployeeGetSkillsGetApplicationService;
import com.amdocs.digital.ms.coe.dashboard.resources.implementation.EmployeeApiImpl.EmployeeGetSkillsGetParameters;
import com.amdocs.digital.ms.coe.dashboard.resources.implementation.EmployeeApiImpl.IEmployeeGetSkillsGetDelegate;
import com.amdocs.msbase.queryparameters.Filter;
import com.amdocs.msbase.queryparameters.PaginationInfo;
import com.amdocs.msbase.queryparameters.SelectedAttributes;
import com.amdocs.msbase.queryparameters.SortFields;
import java.util.List;
import org.springframework.http.ResponseEntity;

public class EmployeeGetSkillsGetDelegate implements IEmployeeGetSkillsGetDelegate
{
	@Inject
	protected IEmployeeGetSkillsGetApplicationService employeeGetSkillsGetApplicationService;

	@Override
	public ResponseEntity<List<String>> execute(EmployeeGetSkillsGetParameters parameters)
	{
		Filter filterConditions = parameters.getFilterConditions();
		PaginationInfo paginationInfo = parameters.getPaginationInfo();
		SelectedAttributes selectAttributes = parameters.getSelectAttributes();
		SortFields sortFields = parameters.getSortFields();

		List<String> response = employeeGetSkillsGetApplicationService.employeeGetSkillsGet(filterConditions, paginationInfo, selectAttributes, sortFields);
		return ResponseEntity.ok(response);
	}
}