//This code was generated by MS-Builder
package com.amdocs.digital.ms.coe.dashboard.gateways.config;

import org.springframework.context.annotation.Configuration;


/**
 * Gateways services configuration file.
 */
@Configuration
public class GatewayApplicationServiceConfig {

}
