//This code was generated by MS-Builder
package com.amdocs.digital.ms.coe.dashboard.business.repository.dto.interfaces;

import java.io.Serializable;

public interface IAdminDTO extends Serializable
{
	public String getAdminEmail();
	public void setAdminEmail(String adminEmail);

	public String getAdminPassword();
	public void setAdminPassword(String adminPassword);

}