//This code was generated by MS-Builder
package com.amdocs.digital.ms.coe.dashboard.business.repository.dto.interfaces;

import java.io.Serializable;
import java.util.List;

public interface IEmployeeDTO extends Serializable
{
	public String getAdditionalInfo();
	public void setAdditionalInfo(String additionalInfo);

	public String getAmdocsExperience();
	public void setAmdocsExperience(String amdocsExperience);

	public String getAmdocsJourney();
	public void setAmdocsJourney(String amdocsJourney);

	public Boolean getApproved();
	public void setApproved(Boolean approved);

	public String getAreaOfCriticalIssue();
	public void setAreaOfCriticalIssue(String areaOfCriticalIssue);

	public Boolean getContributedToDesign();
	public void setContributedToDesign(Boolean contributedToDesign);

	public String getCurrentAccount();
	public void setCurrentAccount(String currentAccount);

	public String getDevOpsKnowledge();
	public void setDevOpsKnowledge(String devOpsKnowledge);

	public String getEmpDesc();
	public void setEmpDesc(String empDesc);

	public String getEmpEmail();
	public void setEmpEmail(String empEmail);

	public String getEmpId();
	public void setEmpId(String empId);

	public String getEmpImage();
	public void setEmpImage(String empImage);

	public String getEmpName();
	public void setEmpName(String empName);

	public String getEmpPassword();
	public void setEmpPassword(String empPassword);

	public String getEmpRole();
	public void setEmpRole(String empRole);

	public Boolean getEngagementActivityContribution();
	public void setEngagementActivityContribution(Boolean engagementActivityContribution);

	public Boolean getExplorationInterest();
	public void setExplorationInterest(Boolean explorationInterest);

	public List<String> getFunctionalKnowledge();
	public void setFunctionalKnowledge(List<String> functionalKnowledge);

	public String getHobbiesSports();
	public void setHobbiesSports(String hobbiesSports);

	public Boolean getMentoringAbility();
	public void setMentoringAbility(Boolean mentoringAbility);

	public Integer getPresentationSkills();
	public void setPresentationSkills(Integer presentationSkills);

	public List<String> getPrimaryProductSubdomain();
	public void setPrimaryProductSubdomain(List<String> primaryProductSubdomain);

	public List<String> getPrimaryTechSkill();
	public void setPrimaryTechSkill(List<String> primaryTechSkill);

	public String getProductionSupport();
	public void setProductionSupport(String productionSupport);

	public List<String> getSecondaryProduct();
	public void setSecondaryProduct(List<String> secondaryProduct);

	public List<String> getSecondaryTechSkill();
	public void setSecondaryTechSkill(List<String> secondaryTechSkill);

	public String getSupervisorName();
	public void setSupervisorName(String supervisorName);

	public String getTotalExperience();
	public void setTotalExperience(String totalExperience);

}