//This code was generated by MS-Builder
package com.amdocs.digital.ms.coe.dashboard.business.repository.dto.interfaces;

import java.io.Serializable;

public interface IInlineResponse400DTO extends Serializable
{
	public Object getEmployee();
	public void setEmployee(Object employee);

}