//This code was generated by MS-Builder
package com.amdocs.digital.ms.coe.dashboard.business.repository.dto.interfaces;

import java.io.Serializable;
import com.amdocs.digital.ms.coe.dashboard.business.repository.dto.interfaces.IEmployeeDTO;

public interface ILoginResponseDTO extends Serializable
{
	public IEmployeeDTO getEmployee();
	public void setEmployee(IEmployeeDTO employee);

	public String getToken();
	public void setToken(String token);

}